[package]
name = "chipmunk"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bytes = { version = "1.6.1", features = ["serde"] }
chrono = "0.4.38"
serde = { version = "1.0.204", features = ["derive"] }

[dev-dependencies]
tempdir = "0.3.7"
walkdir = "2.5.0"
